// =========================
// 2026-04-12 06:28 PM America/Toronto
// PATTERN DETECTION TYPES
// =========================
//
// PURPOSE:
// Central type definitions for the pattern detection layer.
//
// CURRENT DESIGN:
// This layer supports two pattern categories:
//
// 1. atomic
//    A single isolated structural fact.
//    Example: scaled_into_position
//
// 2. composite
//    A higher-order structural pattern made from multiple conditions.
//    Example: multi_build_full_exit
//
// IMPORTANT:
// We are ONLY using a simple classification field right now.
// We are NOT yet implementing a full dependency system between
// atomic and composite patterns.
//
// FUTURE EXPANSION MAY INCLUDE:
// - explicit composite dependency metadata
// - pattern suppression rules
// - composite prioritization
// - family-level deduplication
// - downstream preference for composite patterns
//
// RULES:
// - Detection layer uses PatternInput only
// - No scoring
// - No coaching
// - No interpretation
//

import type { PatternInput } from "../../pattern-input/types/pattern-input";

export type PatternType = "atomic" | "composite";

export type StructuralLevel =
  | "atomic"
  | "structural_composite"
  | "storyline_composite";

export interface PatternMatchResult {
  matched: boolean;
  evidence: Record<string, unknown>;
  thresholdsUsed: Record<string, number>;
}

export interface PatternDefinition {
  id: string;
  name: string;
  family: string;
  patternType: PatternType;
  structuralLevel: StructuralLevel;
  evaluate: (input: PatternInput) => PatternMatchResult;
}

export interface DetectedPattern {
  patternId: string;
  patternName: string;
  family: string;
  patternType: PatternType;
  structuralLevel: StructuralLevel;
  evidence: Record<string, unknown>;
  thresholdsUsed: Record<string, number>;
}

export interface PatternDetectionResult {
  detectedPatterns: DetectedPattern[];
}

export const PATTERN_FAMILIES = {
  EXECUTION_FREQUENCY: "execution_frequency",
  POSITION_BUILDING: "position_building",
  POSITION_REDUCTION: "position_reduction",
  POSITION_STRUCTURE: "position_structure",
  TRADE_DURATION: "trade_duration",
  TRADE_EXCURSION: "trade_excursion",
  TRADE_CLOSURE: "trade_closure",
  ENTRY_CONTEXT: "entry_context",
  ENTRY_QUALITY: "entry_quality",
  EXIT_QUALITY: "exit_quality",
  SCALING_QUALITY: "scaling_quality",
} as const;

export const THRESHOLDS = {
  EXECUTION_FREQUENCY: {
    HIGH_MIN_EXECUTIONS_PER_MINUTE: 2,
    LOW_MAX_EXECUTIONS_PER_MINUTE: 0.3,
  },
  POSITION_BUILDING: {
    MULTI_INCREASE_MIN_EVENTS: 2,
    SINGLE_BUILD_MAX_INCREASE_EVENTS: 1,
  },
  POSITION_REDUCTION: {
    MULTI_DECREASE_MIN_EVENTS: 2,
    INTO_STRENGTH_MIN_RANGE_POSITION: 0.7,
    INTO_WEAKNESS_MAX_RANGE_POSITION: 0.3,
    ABOVE_BASIS_MIN_AVERAGE_PCT: 0.02,
    BELOW_BASIS_MAX_AVERAGE_PCT: -0.01,
    PROFIT_PROTECTION_MAX_GIVEBACK_PCT: 0.25,
    FAILED_PROFIT_PROTECTION_MIN_GIVEBACK_PCT: 0.5,
    FAILED_PROFIT_PROTECTION_MIN_PEAK_OPEN_PROFIT_PCT_OF_BASIS: 0.05,
    REDUCTION_AFTER_RECENT_RUN_UP_MIN_PCT: 0.05,
    REDUCTION_AFTER_RECENT_DROP_MIN_PCT: 0.05,
    HELD_THROUGH_DANGER_MIN_DRAWDOWN_FROM_PEAK_PCT_OF_BASIS: 0.08,
    DELAYED_RISK_RESPONSE_MIN_DRAWDOWN_FROM_PEAK_PCT_OF_BASIS: 0.08,
    DELAYED_RISK_RESPONSE_MIN_SECONDS_TO_FIRST_REDUCTION: 60,
    DELAYED_RISK_RESPONSE_FAILED_PROTECTION_MIN_GIVEBACK_PCT: 0.5,
    TIMELY_RISK_RESPONSE_MAX_SECONDS_TO_FIRST_REDUCTION: 60,
  },
  TRADE_DURATION: {
    QUICK_MAX_DURATION_SECONDS: 120,
    EXTENDED_MIN_DURATION_SECONDS: 900,
  },
  TRADE_EXCURSION: {
    HIGH_MFE_MIN_PCT: 0.05,
    HIGH_MAE_MIN_PCT: 0.05,
  },
  TRADE_CLOSURE: {
    MIN_REMAINING_POSITION_FOR_PARTIAL: 1,
  },
  ENTRY_CONTEXT: {
    LOW_RANGE_ENTRY_MAX_POSITION: 0.3,
    HIGH_RANGE_ENTRY_MIN_POSITION: 0.7,
    NEAR_LOW_MAX_POSITION: 0.2,
    NEAR_HIGH_MIN_POSITION: 0.8,
    FAVORABLE_REMAINING_UPSIDE_MIN_CAPTURED_MFE: 0.6,
    LIMITED_REMAINING_UPSIDE_MAX_CAPTURED_MFE: 0.3,
    RECENT_RUN_UP_MIN_PCT: 0.05,
    RECENT_DROP_MIN_PCT: 0.05,
    RECENT_DIRECTIONAL_CANDLE_EDGE: 1,
  },
  ENTRY_QUALITY: {
    ADVANTAGED_MAX_RANGE_POSITION: 0.3,
    ADVANTAGED_MIN_CAPTURED_MFE: 0.6,
    ADVANTAGED_MAX_ADVERSE_AFTER_ENTRY_PCT: 0.02,

    DISADVANTAGED_MIN_RANGE_POSITION: 0.7,
    DISADVANTAGED_MAX_CAPTURED_MFE: 0.3,
    DISADVANTAGED_MIN_ADVERSE_AFTER_ENTRY_PCT: 0.02,

    EFFICIENT_MIN_CAPTURED_MFE: 0.6,
    EFFICIENT_MAX_ADVERSE_AFTER_ENTRY_PCT: 0.02,

    INEFFICIENT_MAX_CAPTURED_MFE: 0.3,
    INEFFICIENT_MIN_ADVERSE_AFTER_ENTRY_PCT: 0.02,

    LATE_FAVORABLE_EXTENSION_MIN_NET_MOVE_PCT: 0.03,
    BREAKOUT_ENTRY_MIN_NET_MOVE_PCT: 0.03,
    BREAKOUT_ENTRY_MAX_NET_MOVE_PCT: 0.06,
    MEASURED_FAVORABLE_EXTENSION_MAX_NET_MOVE_PCT: 0.06,
    OVEREXTENDED_CHASE_MIN_NET_MOVE_PCT: 0.06,
    FAILED_BREAKOUT_MAX_CAPTURED_MFE: 0.3,
    FAILED_BREAKOUT_MIN_ADVERSE_AFTER_ENTRY_PCT: 0.02,
    RECLAIM_ENTRY_MIN_REFERENCE_BREAK_DEPTH_PCT: 0.01,
    RECLAIM_ENTRY_MAX_DISTANCE_FROM_REFERENCE_PCT: 0.03,
    RECLAIM_ENTRY_MIN_CONFIRMATION_CANDLES: 1,
    FAILED_RECLAIM_MAX_CAPTURED_MFE: 0.3,
    FAILED_RECLAIM_MIN_ADVERSE_AFTER_ENTRY_PCT: 0.02,
    MEAN_REVERSION_MIN_COUNTER_MOVE_PCT: 0.08,
    MEAN_REVERSION_MAX_NET_MOVE_PCT: 0,
    FAILED_MEAN_REVERSION_MAX_CAPTURED_MFE: 0.3,
    FAILED_MEAN_REVERSION_MIN_ADVERSE_AFTER_ENTRY_PCT: 0.02,
    OPENING_RANGE_BREAKOUT_MAX_DISTANCE_BEYOND_RANGE_PCT: 0.03,
    OPENING_RANGE_BREAKOUT_CHASE_MIN_DISTANCE_BEYOND_RANGE_PCT: 0.03,
    MARKET_OPEN_BREAKOUT_MAX_DISTANCE_BEYOND_RANGE_PCT: 0.03,
    MARKET_OPEN_BREAKOUT_CHASE_MIN_DISTANCE_BEYOND_RANGE_PCT: 0.03,
    CONSTRUCTIVE_PULLBACK_MAX_NET_MOVE_PCT: -0.02,
    DEEP_CONSTRUCTIVE_PULLBACK_MIN_COUNTER_MOVE_PCT: 0.08,
    DEEP_CONSTRUCTIVE_PULLBACK_MAX_NET_MOVE_PCT: -0.05,
    DEEP_WEAK_PULLBACK_MIN_COUNTER_MOVE_PCT: 0.08,
    DEEP_WEAK_PULLBACK_MAX_NET_MOVE_PCT: -0.05,
  },
  EXIT_QUALITY: {
    HIGH_CAPTURE_MIN_REALIZED_CAPTURE: 0.7,
    HIGH_CAPTURE_MIN_EXIT_RANGE_POSITION: 0.7,

    MODERATE_CAPTURE_MIN_REALIZED_CAPTURE: 0.5,
    MODERATE_CAPTURE_MAX_REALIZED_CAPTURE: 0.7,

    LOW_CAPTURE_MAX_REALIZED_CAPTURE: 0.3,

    LIMITED_GIVEBACK_MAX_LEFT_ON_TABLE: 0.03,
    MEANINGFUL_GIVEBACK_MIN_LEFT_ON_TABLE: 0.05,
    PEAK_PROFIT_GIVEBACK_MIN_PCT: 0.5,
    PEAK_PROFIT_GIVEBACK_MIN_OPEN_PROFIT_PCT_OF_BASIS: 0.05,
    PARTIAL_EXIT_ADVERSE_FOLLOWTHROUGH_MIN_PCT: 0.03,
    MISSED_POST_EXIT_CONTINUATION_MIN_FAVORABLE_PCT: 0.03,
    MISSED_POST_EXIT_CONTINUATION_MIN_NET_END_PCT: 0.01,
    EXIT_AVOIDED_ADVERSE_FOLLOWTHROUGH_MIN_ADVERSE_PCT: 0.02,
    EXIT_AVOIDED_ADVERSE_FOLLOWTHROUGH_MAX_NET_END_PCT: -0.005,
    DEFENSIVE_EXIT_AFTER_DETERIORATION_MIN_GIVEBACK_PCT: 0.5,
    PREMATURE_FINAL_EXIT_MAX_GIVEBACK_PCT: 0.25,
    FEARFUL_EXIT_AFTER_WEAKENING_MAX_REALIZED_CAPTURE: 0.3,
    DISCIPLINED_DEFENSIVE_EXIT_MAX_GIVEBACK_PCT: 0.35,
    STOP_LIKE_FORCED_EXIT_MAX_REALIZED_CAPTURE: 0.35,
    STOP_LIKE_FORCED_EXIT_MIN_DRAWDOWN_FROM_PEAK_PCT_OF_BASIS: 0.08,

    NEAR_FAVORABLE_EXTREME_MIN_RANGE_POSITION: 0.8,
  },
  SCALING_QUALITY: {
    STRUCTURED_MIN_INCREASES: 2,

    BALANCED_MIN_INCREASES: 2,
    BALANCED_MIN_DECREASES: 1,

    ONE_SIDED_MIN_INCREASES: 2,
    ONE_SIDED_REQUIRED_DECREASES: 0,

    UNDERUTILIZED_MAX_INCREASES: 1,
    UNDERUTILIZED_MIN_MFE_PCT: 0.05,

    ADD_ABOVE_BASIS_MIN_AVERAGE_PCT: 0.02,
    ADD_INTO_STRENGTH_MIN_RANGE_POSITION: 0.7,
    ADD_INTO_STRENGTH_MIN_AVERAGE_PCT: 0.02,
    ADD_INTO_WEAKNESS_MAX_RANGE_POSITION: 0.3,
    ADD_INTO_WEAKNESS_MAX_AVERAGE_PCT: -0.01,
    ADD_AFTER_RECENT_RUN_UP_MIN_PCT: 0.05,
    ADD_AFTER_RECENT_DROP_MIN_PCT: 0.05,
    BALANCED_WITH_PROFIT_PROTECTION_MAX_GIVEBACK_PCT: 0.25,
    AGGRESSIVE_ADDING_MIN_ADD_EVENTS: 2,
    AGGRESSIVE_ADDING_FAILED_PROTECTION_MIN_GIVEBACK_PCT: 0.5,
    AGGRESSIVE_ADDING_FAILED_PROTECTION_MIN_PEAK_OPEN_PROFIT_PCT_OF_BASIS: 0.05,
    READD_AFTER_DELAYED_RISK_RESPONSE_MIN_GIVEBACK_PCT: 0.5,
    CONSTRUCTIVE_READD_MAX_GIVEBACK_PCT: 0.25,
    CONSTRUCTIVE_RECOVERY_MIN_PEAK_OPEN_PROFIT_PCT_OF_BASIS: 0.05,
    CONSTRUCTIVE_RECOVERY_MAX_GIVEBACK_PCT: 0.35,
    RECOVERY_FAILED_PROTECTION_MIN_GIVEBACK_PCT: 0.5,
    MULTI_CYCLE_MIN_PARTIAL_EXITS: 2,
    MULTI_CYCLE_MIN_READD_COUNT: 2,
    MULTI_CYCLE_CONSTRUCTIVE_MAX_GIVEBACK_PCT: 0.35,
    MULTI_CYCLE_UNSTABLE_MIN_GIVEBACK_PCT: 0.5,
    LATE_CHASE_REENTRY_MIN_READD_RUN_UP_COUNT: 1,
    LATE_CHASE_REENTRY_MIN_FAVORABLE_MOVE_AFTER_TRIM_PCT: 0.03,
    GOOD_PULLBACK_REENTRY_MIN_READD_DROP_COUNT: 1,
    GOOD_PULLBACK_REENTRY_MAX_ADVERSE_MOVE_AFTER_TRIM_PCT: 0.03,
    CONSTRUCTIVE_REENTRY_MIN_STRONGER_FAVORABLE_COUNT: 1,
    CONSTRUCTIVE_REENTRY_MIN_FAVORABLE_FOLLOWTHROUGH_PCT: 0.025,
    DETERIORATING_REENTRY_MIN_STRONGER_ADVERSE_COUNT: 1,
    DETERIORATING_REENTRY_MIN_ADVERSE_FOLLOWTHROUGH_PCT: 0.025,
  },
} as const;
