import { compareUnicodeCodePoints } from "../../../domain/canonical";
import type { CanonicalContentDigest } from "../../../domain/identity";
import { finalizeContentAddressedAuthority, contractFailure, type AnalyticalContractFailure } from "../../contracts";
import { buildTradeQueryComparison, buildTradeQueryPlan, type TradeQueryAuthority, type TradeQueryComparison, type TradeQueryFilter, type TradeQueryGrouping, type TradeQueryPlan, type TradeQueryMetricKey, TRADE_QUERY_PLAN_KEY, TRADE_QUERY_PLAN_SEMANTIC_VERSION, TRADE_QUERY_PLAN_VERSION, TRADE_QUERY_POLICY } from "../contracts";
import { executeTradeQuery } from "../execution";
import type { AnalyticalPartitionReceipt } from "../../dataset";
import type { VerifiedTradeQueryDatasetSource } from "../gateway";
import { openReadOnlyTradeQueryGateway } from "../gateway";

export const TRADE_QUERY_PRESET_VERSION = "ti_v3_execution_only_analytics_preset_v1" as const;
export const GA1_B_PRESET_KEYS = ["analyze_performance_by_price_range", "analyze_time_of_day", "analyze_trade_sequence_performance", "analyze_after_loss_behavior", "analyze_after_win_behavior", "analyze_ticker_repeat_attempts", "analyze_holding_time", "analyze_long_vs_short", "analyze_position_size_performance", "compare_periods"] as const;
export type Ga1BPresetKey = typeof GA1_B_PRESET_KEYS[number];
export interface Ga1BPresetInput { readonly presetKey: Ga1BPresetKey; readonly authority: TradeQueryAuthority; readonly filters?: readonly TradeQueryFilter[]; readonly baselineFilters?: readonly TradeQueryFilter[]; readonly timeBucketMinutes?: string; readonly limits?: Readonly<Partial<{ groupLimit: string; resultRowLimit: string; evidencePerGroup: string; totalEvidenceLimit: string; diagnosticLimit: string }>>; }
export interface Ga1BPreset { readonly schemaVersion: typeof TRADE_QUERY_PRESET_VERSION; readonly presetKey: Ga1BPresetKey; readonly presetVersion: "v1"; readonly primaryPlan: TradeQueryPlan; readonly baselinePlan: TradeQueryPlan | null; readonly minimumSample: string; readonly unavailablePolicy: string; readonly evidencePolicy: string; readonly counterexamplePolicy: string; readonly outlierPolicy: string; readonly wordingPolicy: string; readonly presetDigest: CanonicalContentDigest; }
export interface Ga1BPresetExecution { readonly preset: Ga1BPreset; readonly primaryResultDigest: CanonicalContentDigest; readonly baselineResultDigest: CanonicalContentDigest | null; readonly comparison: TradeQueryComparison | null; }

const METRICS: readonly TradeQueryMetricKey[] = Object.freeze(["candidate_count", "included_count", "excluded_count", "net_pnl", "gross_pnl", "signed_charges", "average_pnl", "median_pnl", "expectancy", "win_count", "loss_count", "flat_count", "win_rate", "profit_factor", "average_holding_time", "median_holding_time", "average_share_quantity", "average_entry_notional", "average_position_size", "largest_winner_contribution", "largest_loser_contribution", "net_pnl_excluding_largest_winner", "net_pnl_excluding_largest_loser"]);
function grouping(input: Ga1BPresetInput): TradeQueryGrouping { switch (input.presetKey) { case "analyze_performance_by_price_range": return { kind: "entry_price_range", boundaries: ["1", "5", "10"] }; case "analyze_time_of_day": return { kind: "time_bucket", source: "entry", bucketMinutes: input.timeBucketMinutes ?? "60" }; case "analyze_trade_sequence_performance": return { kind: "trade_sequence" }; case "analyze_ticker_repeat_attempts": return { kind: "repeat_attempt" }; case "analyze_holding_time": return { kind: "holding_time_bucket", boundariesSeconds: ["60", "300", "900", "3600"] }; case "analyze_long_vs_short": return { kind: "direction" }; case "analyze_position_size_performance": return { kind: "position_size_bucket", boundaries: ["100", "500", "1000", "5000"] }; default: return { kind: "aggregate" }; } }
function additionalFilter(key: Ga1BPresetKey): TradeQueryFilter | null { if (key === "analyze_after_loss_behavior") return { kind: "previous_completed_outcome", values: ["loss"] }; if (key === "analyze_after_win_behavior") return { kind: "previous_completed_outcome", values: ["gain"] }; return null; }
function buildPlan(input: Ga1BPresetInput, filters: readonly TradeQueryFilter[]): ReturnType<typeof buildTradeQueryPlan> { return buildTradeQueryPlan({ schemaVersion: TRADE_QUERY_PLAN_VERSION, queryPlanKey: TRADE_QUERY_PLAN_KEY, queryPlanVersion: TRADE_QUERY_PLAN_SEMANTIC_VERSION, authority: { snapshotDigest: input.authority.datasetReceipt.snapshotDigest, canonicalFilterDigest: input.authority.datasetReceipt.filterDigest, datasetReceiptDigest: input.authority.datasetReceipt.receiptDigest, datasetDerivationDigest: input.authority.datasetDerivationReceipt.derivationDigest, partitionDigest: input.authority.partitionReceipt.partitionDigest, currency: input.authority.partitionReceipt.currency, ownerScope: input.authority.partitionReceipt.ownerScope, accountScope: input.authority.partitionReceipt.accountScope }, filters, grouping: grouping(input), metrics: METRICS, ordering: [{ by: "group_identity", metricKey: null, direction: "ascending" }], limits: { groupLimit: input.limits?.groupLimit ?? "64", resultRowLimit: input.limits?.resultRowLimit ?? "64", evidencePerGroup: input.limits?.evidencePerGroup ?? "8", totalEvidenceLimit: input.limits?.totalEvidenceLimit ?? "128", diagnosticLimit: input.limits?.diagnosticLimit ?? "32" }, policies: TRADE_QUERY_POLICY }, input.authority); }

export function compileGa1BPreset(input: Ga1BPresetInput): { readonly ok: true; readonly value: Ga1BPreset } | { readonly ok: false; readonly error: AnalyticalContractFailure } {
  if (!GA1_B_PRESET_KEYS.includes(input.presetKey)) return contractFailure("ti_v3_analytics_contract_invalid", "$.presetKey");
  const required = additionalFilter(input.presetKey); const filters = [...(input.filters ?? [])]; if (required !== null) { if (filters.some((item) => item.kind === required.kind)) return contractFailure("ti_v3_analytics_contract_duplicate_identity", "$.filters"); filters.push(required); }
  const primary = buildPlan(input, filters); if (!primary.ok) return primary;
  if (input.presetKey !== "compare_periods" && input.baselineFilters !== undefined) return contractFailure("ti_v3_analytics_contract_invalid", "$.baselineFilters");
  const baseline = input.presetKey === "compare_periods" ? buildPlan(input, input.baselineFilters ?? []) : null; if (baseline !== null && !baseline.ok) return baseline;
  const built = finalizeContentAddressedAuthority("trade_query_preset", { schemaVersion: TRADE_QUERY_PRESET_VERSION, presetKey: input.presetKey, presetVersion: "v1", primaryPlan: primary.value, baselinePlan: baseline?.value ?? null, minimumSample: "1", unavailablePolicy: "exact_metrics_declare_unavailable_per_registry", evidencePolicy: "bounded_support_and_counterexample_evidence", counterexamplePolicy: "deterministic_opposite_outcome_first", outlierPolicy: "include_largest_trade_contribution_and_leave_largest_out_metrics", wordingPolicy: "structured_results_only_no_causal_or_predictive_claims" }, "presetDigest");
  return built.ok ? { ok: true, value: built.value as Ga1BPreset } : built;
}

export function executeGa1BPreset(args: Readonly<{ readonly source: VerifiedTradeQueryDatasetSource; readonly partitionReceipt: AnalyticalPartitionReceipt; readonly preset: Ga1BPreset; }>): { readonly ok: true; readonly value: Ga1BPresetExecution } | { readonly ok: false; readonly error: AnalyticalContractFailure } {
  const gateway = openReadOnlyTradeQueryGateway(args.source, args.partitionReceipt); if (!gateway.ok) return gateway;
  const primary = executeTradeQuery({ source: args.source, partitionReceipt: args.partitionReceipt, queryPlan: args.preset.primaryPlan }); if (!primary.ok) return primary;
  if (args.preset.baselinePlan === null) return { ok: true, value: Object.freeze({ preset: args.preset, primaryResultDigest: primary.value.resultDigest, baselineResultDigest: null, comparison: null }) };
  const baseline = executeTradeQuery({ source: args.source, partitionReceipt: args.partitionReceipt, queryPlan: args.preset.baselinePlan }); if (!baseline.ok) return baseline;
  const comparison = buildTradeQueryComparison(primary.value, baseline.value, gateway.value.authority);
  if (!comparison.ok) return comparison;
  return { ok: true, value: Object.freeze({ preset: args.preset, primaryResultDigest: primary.value.resultDigest, baselineResultDigest: baseline.value.resultDigest, comparison: comparison.value }) };
}
