import { compareUnicodeCodePoints, serializeCanonicalValue } from "../../../domain/canonical";
import type { CanonicalContentDigest } from "../../../domain/identity";
import { contractFailure, finalizeContentAddressedAuthority, validateClaimedDigest, validateContractRecord, type AnalyticalContractFailure } from "../../contracts";
import { buildTradeQueryComparison, buildTradeQueryPlan, verifyTradeQueryPlan, type TradeQueryAuthority, type TradeQueryComparison, type TradeQueryFilter, type TradeQueryGrouping, type TradeQueryPlan, type TradeQueryMetricKey, type TradeQueryResult, TRADE_QUERY_PLAN_KEY, TRADE_QUERY_PLAN_SEMANTIC_VERSION, TRADE_QUERY_PLAN_VERSION, TRADE_QUERY_POLICY } from "../contracts";
import { executeTradeQuery } from "../execution";
import type { AnalyticalPartitionReceipt } from "../../dataset";
import type { VerifiedTradeQueryDatasetSource } from "../gateway";
import { openReadOnlyTradeQueryGateway } from "../gateway";

export const TRADE_QUERY_PRESET_VERSION = "ti_v3_execution_only_analytics_preset_v1" as const;
export const TRADE_QUERY_PRESET_EXECUTION_VERSION = "ti_v3_execution_only_analytics_preset_execution_v1" as const;
export const GA1_B_PRESET_KEYS = ["analyze_performance_by_price_range", "analyze_time_of_day", "analyze_trade_sequence_performance", "analyze_after_loss_behavior", "analyze_after_win_behavior", "analyze_ticker_repeat_attempts", "analyze_holding_time", "analyze_long_vs_short", "analyze_position_size_performance", "compare_periods"] as const;
export type Ga1BPresetKey = typeof GA1_B_PRESET_KEYS[number];
export interface Ga1BPresetInput { readonly presetKey: Ga1BPresetKey; readonly authority: TradeQueryAuthority; readonly filters?: readonly TradeQueryFilter[]; readonly baselineFilters?: readonly TradeQueryFilter[]; readonly timeBucketMinutes?: string; readonly limits?: Readonly<Partial<{ groupLimit: string; resultRowLimit: string; evidencePerGroup: string; totalEvidenceLimit: string; diagnosticLimit: string }>>; }
export interface Ga1BPreset { readonly schemaVersion: typeof TRADE_QUERY_PRESET_VERSION; readonly presetKey: Ga1BPresetKey; readonly presetVersion: "v1"; readonly primaryPlan: TradeQueryPlan; readonly baselinePlan: TradeQueryPlan | null; readonly minimumSample: string; readonly unavailablePolicy: string; readonly evidencePolicy: string; readonly counterexamplePolicy: string; readonly outlierPolicy: string; readonly wordingPolicy: string; readonly presetDigest: CanonicalContentDigest; }
export interface Ga1BPresetExecution { readonly schemaVersion: typeof TRADE_QUERY_PRESET_EXECUTION_VERSION; readonly preset: Ga1BPreset; readonly presetDigest: CanonicalContentDigest; readonly primaryPlanDigest: CanonicalContentDigest; readonly primaryResult: TradeQueryResult; readonly primaryResultDigest: CanonicalContentDigest; readonly baselinePlanDigest: CanonicalContentDigest | null; readonly baselineResult: TradeQueryResult | null; readonly baselineResultDigest: CanonicalContentDigest | null; readonly comparison: TradeQueryComparison | null; readonly comparisonDigest: CanonicalContentDigest | null; readonly datasetReceiptDigest: CanonicalContentDigest; readonly datasetDerivationDigest: CanonicalContentDigest; readonly partitionDigest: CanonicalContentDigest; readonly ownerScope: readonly string[]; readonly accountScope: readonly string[]; readonly currency: string; readonly candidateCount: string; readonly includedCount: string; readonly excludedCount: string; readonly evidenceDigests: readonly CanonicalContentDigest[]; readonly limitationCodes: readonly string[]; readonly executionResultDigest: CanonicalContentDigest; }

const METRICS: readonly TradeQueryMetricKey[] = Object.freeze(["candidate_count", "included_count", "excluded_count", "net_pnl", "gross_pnl", "signed_charges", "average_pnl", "median_pnl", "expectancy", "win_count", "loss_count", "flat_count", "win_rate", "profit_factor", "average_holding_time", "median_holding_time", "average_share_quantity", "average_entry_notional", "average_position_size", "largest_winner_contribution", "largest_loser_contribution", "net_pnl_excluding_largest_winner", "net_pnl_excluding_largest_loser"]);
const policy = Object.freeze({ minimumSample: "1", unavailablePolicy: "exact_metrics_declare_unavailable_per_registry", evidencePolicy: "bounded_support_and_counterexample_evidence", counterexamplePolicy: "deterministic_opposite_outcome_first", outlierPolicy: "include_largest_trade_contribution_and_leave_largest_out_metrics", wordingPolicy: "structured_results_only_no_causal_or_predictive_claims" });
function grouping(input: Ga1BPresetInput): TradeQueryGrouping { switch (input.presetKey) { case "analyze_performance_by_price_range": return { kind: "entry_price_range", boundaries: ["1", "5", "10"] }; case "analyze_time_of_day": return { kind: "time_bucket", source: "entry", bucketMinutes: input.timeBucketMinutes ?? "60" }; case "analyze_trade_sequence_performance": return { kind: "trade_sequence_bucket" }; case "analyze_ticker_repeat_attempts": return { kind: "repeat_attempt_bucket" }; case "analyze_holding_time": return { kind: "holding_time_bucket", boundariesSeconds: ["60", "300", "900", "3600"] }; case "analyze_long_vs_short": return { kind: "direction" }; case "analyze_position_size_performance": return { kind: "position_size_bucket", boundaries: ["100", "500", "1000", "5000"] }; default: return { kind: "aggregate" }; } }
function requiredFilter(key: Ga1BPresetKey): TradeQueryFilter | null { return key === "analyze_after_loss_behavior" ? { kind: "previous_completed_outcome", values: ["loss"] } : key === "analyze_after_win_behavior" ? { kind: "previous_completed_outcome", values: ["gain"] } : null; }
function buildPlan(input: Ga1BPresetInput, filters: readonly TradeQueryFilter[]) { return buildTradeQueryPlan({ schemaVersion: TRADE_QUERY_PLAN_VERSION, queryPlanKey: TRADE_QUERY_PLAN_KEY, queryPlanVersion: TRADE_QUERY_PLAN_SEMANTIC_VERSION, authority: { snapshotDigest: input.authority.datasetReceipt.snapshotDigest, canonicalFilterDigest: input.authority.datasetReceipt.filterDigest, datasetReceiptDigest: input.authority.datasetReceipt.receiptDigest, datasetDerivationDigest: input.authority.datasetDerivationReceipt.derivationDigest, partitionDigest: input.authority.partitionReceipt.partitionDigest, currency: input.authority.partitionReceipt.currency, ownerScope: input.authority.partitionReceipt.ownerScope, accountScope: input.authority.partitionReceipt.accountScope }, filters, grouping: grouping(input), metrics: METRICS, ordering: input.presetKey === "analyze_trade_sequence_performance" ? [] : [{ by: "group_identity", metricKey: null, direction: "ascending" }], limits: { groupLimit: input.limits?.groupLimit ?? "64", resultRowLimit: input.limits?.resultRowLimit ?? "64", evidencePerGroup: input.limits?.evidencePerGroup ?? "8", totalEvidenceLimit: input.limits?.totalEvidenceLimit ?? "128", diagnosticLimit: input.limits?.diagnosticLimit ?? "32" }, policies: TRADE_QUERY_POLICY }, input.authority); }
function equal(left: unknown, right: unknown): boolean { const a = serializeCanonicalValue(left); const b = serializeCanonicalValue(right); return a.ok && b.ok && a.value.json === b.value.json; }

function strictPresetInput(input: unknown): { readonly ok: true; readonly value: Ga1BPresetInput } | { readonly ok: false; readonly error: AnalyticalContractFailure } {
  if (typeof input !== "object" || input === null || Array.isArray(input) || Object.getPrototypeOf(input) !== Object.prototype) return contractFailure("ti_v3_analytics_contract_invalid", "$");
  const allowed = new Set(["presetKey", "authority", "filters", "baselineFilters", "timeBucketMinutes", "limits"]);
  const descriptors = Object.getOwnPropertyDescriptors(input); const normalized: Record<string, unknown> = {};
  for (const key of Reflect.ownKeys(descriptors)) {
    if (typeof key !== "string" || !allowed.has(key)) return contractFailure("ti_v3_analytics_contract_invalid", "$");
    const descriptor = descriptors[key]; if (descriptor.get !== undefined || descriptor.set !== undefined || !("value" in descriptor)) return contractFailure("ti_v3_analytics_contract_invalid", `$.${key}`);
    if (descriptor.value !== undefined) normalized[key] = descriptor.value;
  }
  const record = validateContractRecord(normalized, ["presetKey", "authority"], ["filters", "baselineFilters", "timeBucketMinutes", "limits"]); return record.ok ? { ok: true, value: record.value as unknown as Ga1BPresetInput } : record;
}

export function compileGa1BPreset(input: unknown): { readonly ok: true; readonly value: Ga1BPreset } | { readonly ok: false; readonly error: AnalyticalContractFailure } {
  const strict = strictPresetInput(input); if (!strict.ok) return strict; const data = strict.value;
  if (!GA1_B_PRESET_KEYS.includes(data.presetKey)) return contractFailure("ti_v3_analytics_contract_invalid", "$.presetKey");
  if (data.presetKey !== "compare_periods" && data.baselineFilters !== undefined) return contractFailure("ti_v3_analytics_contract_invalid", "$.baselineFilters");
  if (data.presetKey === "compare_periods" && (!Array.isArray(data.baselineFilters) || data.baselineFilters.length === 0)) return contractFailure("ti_v3_analytics_contract_invalid", "$.baselineFilters");
  const required = requiredFilter(data.presetKey); const filters = [...(data.filters ?? [])];
  if (required !== null) { if (filters.some((item) => item.kind === required.kind)) return contractFailure("ti_v3_analytics_contract_duplicate_identity", "$.filters"); filters.push(required); }
  const primary = buildPlan(data, filters); if (!primary.ok) return primary;
  const baseline = data.presetKey === "compare_periods" ? buildPlan(data, data.baselineFilters as readonly TradeQueryFilter[]) : null; if (baseline !== null && !baseline.ok) return baseline;
  if (baseline !== null && baseline.value.queryPlanDigest === primary.value.queryPlanDigest) return contractFailure("ti_v3_analytics_contract_invalid", "$.baselineFilters");
  const addressed = finalizeContentAddressedAuthority("trade_query_preset", { schemaVersion: TRADE_QUERY_PRESET_VERSION, presetKey: data.presetKey, presetVersion: "v1", primaryPlan: primary.value, baselinePlan: baseline?.value ?? null, ...policy }, "presetDigest");
  return addressed.ok ? { ok: true, value: addressed.value as Ga1BPreset } : addressed;
}

export function verifyGa1BPreset(input: unknown, authority: TradeQueryAuthority): { readonly ok: true; readonly value: Ga1BPreset } | { readonly ok: false; readonly error: AnalyticalContractFailure } {
  const record = validateContractRecord(input, ["schemaVersion", "presetKey", "presetVersion", "primaryPlan", "baselinePlan", "minimumSample", "unavailablePolicy", "evidencePolicy", "counterexamplePolicy", "outlierPolicy", "wordingPolicy", "presetDigest"], []); if (!record.ok) return record;
  if (record.value.schemaVersion !== TRADE_QUERY_PRESET_VERSION || record.value.presetVersion !== "v1" || typeof record.value.presetKey !== "string" || !GA1_B_PRESET_KEYS.includes(record.value.presetKey as Ga1BPresetKey)) return contractFailure("ti_v3_analytics_contract_invalid", "$.preset");
  const digest = validateClaimedDigest(record.value.presetDigest, "$.presetDigest", "trade_query_preset"); if (!digest.ok) return digest;
  const primary = verifyTradeQueryPlan(record.value.primaryPlan, authority); if (!primary.ok) return primary;
  const baseline = record.value.baselinePlan === null ? null : verifyTradeQueryPlan(record.value.baselinePlan, authority); if (baseline !== null && !baseline.ok) return baseline;
  const key = record.value.presetKey as Ga1BPresetKey; if ((key === "compare_periods") !== (baseline !== null)) return contractFailure("ti_v3_analytics_contract_invalid", "$.baselinePlan");
  if (baseline !== null && baseline.value.queryPlanDigest === primary.value.queryPlanDigest) return contractFailure("ti_v3_analytics_contract_invalid", "$.baselinePlan");
  const required = requiredFilter(key); const primaryFilters = required === null ? primary.value.filters : primary.value.filters.filter((item) => item.kind !== required.kind);
  const rebuilt = compileGa1BPreset({ presetKey: key, authority, filters: primaryFilters, baselineFilters: baseline?.value.filters, timeBucketMinutes: primary.value.grouping.kind === "time_bucket" ? primary.value.grouping.bucketMinutes : undefined, limits: primary.value.limits });
  return rebuilt.ok && rebuilt.value.presetDigest === digest.value && equal(input, rebuilt.value) ? rebuilt : contractFailure("ti_v3_analytics_contract_digest_mismatch", "$.presetDigest");
}

export function executeGa1BPreset(args: Readonly<{ readonly source: VerifiedTradeQueryDatasetSource; readonly partitionReceipt: AnalyticalPartitionReceipt; readonly preset: Ga1BPreset; }>): { readonly ok: true; readonly value: Ga1BPresetExecution } | { readonly ok: false; readonly error: AnalyticalContractFailure } {
  const gateway = openReadOnlyTradeQueryGateway(args.source, args.partitionReceipt); if (!gateway.ok) return gateway;
  const preset = verifyGa1BPreset(args.preset, gateway.value.authority); if (!preset.ok) return preset;
  const primary = executeTradeQuery({ source: args.source, partitionReceipt: args.partitionReceipt, queryPlan: preset.value.primaryPlan }); if (!primary.ok) return primary;
  const baseline = preset.value.baselinePlan === null ? null : executeTradeQuery({ source: args.source, partitionReceipt: args.partitionReceipt, queryPlan: preset.value.baselinePlan }); if (baseline !== null && !baseline.ok) return baseline;
  const comparison = baseline === null ? null : buildTradeQueryComparison(primary.value, baseline.value, gateway.value.authority); if (comparison !== null && !comparison.ok) return comparison;
  const built = finalizeContentAddressedAuthority("trade_query_preset_execution", { schemaVersion: TRADE_QUERY_PRESET_EXECUTION_VERSION, preset: preset.value, presetDigest: preset.value.presetDigest, primaryPlanDigest: primary.value.normalizedQueryPlan.queryPlanDigest, primaryResult: primary.value, primaryResultDigest: primary.value.resultDigest, baselinePlanDigest: baseline?.value.normalizedQueryPlan.queryPlanDigest ?? null, baselineResult: baseline?.value ?? null, baselineResultDigest: baseline?.value.resultDigest ?? null, comparison: comparison?.value ?? null, comparisonDigest: comparison?.value.comparisonDigest ?? null, datasetReceiptDigest: gateway.value.authority.datasetReceipt.receiptDigest, datasetDerivationDigest: gateway.value.authority.datasetDerivationReceipt.derivationDigest, partitionDigest: gateway.value.authority.partitionReceipt.partitionDigest, ownerScope: gateway.value.authority.partitionReceipt.ownerScope, accountScope: gateway.value.authority.partitionReceipt.accountScope, currency: gateway.value.authority.partitionReceipt.currency, candidateCount: primary.value.candidateCount, includedCount: primary.value.includedCount, excludedCount: primary.value.excludedCount, evidenceDigests: primary.value.evidence.map((item) => item.evidenceDigest).sort(compareUnicodeCodePoints), limitationCodes: primary.value.limitationCodes }, "executionResultDigest");
  return built.ok ? { ok: true, value: built.value as Ga1BPresetExecution } : built;
}

export function verifyGa1BPresetExecution(args: Readonly<{ readonly source: VerifiedTradeQueryDatasetSource; readonly partitionReceipt: AnalyticalPartitionReceipt; readonly execution: unknown; }>): { readonly ok: true; readonly value: Ga1BPresetExecution } | { readonly ok: false; readonly error: AnalyticalContractFailure } {
  const record = validateContractRecord(args.execution, ["schemaVersion", "preset", "presetDigest", "primaryPlanDigest", "primaryResult", "primaryResultDigest", "baselinePlanDigest", "baselineResult", "baselineResultDigest", "comparison", "comparisonDigest", "datasetReceiptDigest", "datasetDerivationDigest", "partitionDigest", "ownerScope", "accountScope", "currency", "candidateCount", "includedCount", "excludedCount", "evidenceDigests", "limitationCodes", "executionResultDigest"], []); if (!record.ok) return record;
  const digest = validateClaimedDigest(record.value.executionResultDigest, "$.executionResultDigest", "trade_query_preset_execution"); if (!digest.ok) return digest;
  const rebuilt = executeGa1BPreset({ source: args.source, partitionReceipt: args.partitionReceipt, preset: record.value.preset as Ga1BPreset });
  return rebuilt.ok && rebuilt.value.executionResultDigest === digest.value && equal(record.value, rebuilt.value) ? rebuilt : contractFailure("ti_v3_analytics_contract_digest_mismatch", "$.executionResultDigest");
}
