import { compareUnicodeCodePoints } from "../../../domain/canonical";
import type { CanonicalContentDigest } from "../../../domain/identity";
import { finalizeContentAddressedAuthority, contractFailure, type AnalyticalContractFailure, type ExactMetricValue } from "../../contracts";
import type { AnalyticalPartitionReceipt } from "../../dataset";
import { applyTradeQueryFilters } from "../filters";
import { openReadOnlyTradeQueryGateway, type VerifiedTradeQueryDatasetSource } from "../gateway";
import { buildQueryRowSemantics, type QueryRowSemantics } from "../execution";
import { calculateTradeQueryMetrics } from "../metrics";
import type { TradeQueryFilter } from "../contracts";
import { verifyTradeQueryResultShape } from "../contracts";
import { isVerifiedTradeQueryExecution } from "../execution/verified-execution";

export const TRADE_QUERY_SIMILARITY_SEARCH_VERSION = "ti_v3_trade_query_similarity_search_v1" as const;
export type SimilarTradeDimension = "direction" | "entry_price" | "entry_time" | "share_quantity" | "entry_notional" | "holding_time" | "sequence_in_session" | "previous_completed_outcome" | "repeat_attempt" | "symbol" | "account";
export interface SimilarTradeSearchRequest { readonly targetTradeKey: string; readonly dimensions: readonly SimilarTradeDimension[]; readonly filters: readonly TradeQueryFilter[]; readonly includeNearMisses: boolean; readonly maximumMatches: string; readonly maximumNearMisses: string; }
export interface SimilarTradeMatch { readonly semanticRoundTripKey: string; readonly rowDigest: CanonicalContentDigest; readonly executionDigests: readonly CanonicalContentDigest[]; readonly occurrenceKeys: readonly string[]; readonly matchedDimensions: readonly SimilarTradeDimension[]; readonly unmatchedDimensions: readonly SimilarTradeDimension[]; readonly unavailableDimensions: readonly SimilarTradeDimension[]; readonly kind: "match" | "near_miss"; }
export interface SimilarTradeSearchResult { readonly schemaVersion: typeof TRADE_QUERY_SIMILARITY_SEARCH_VERSION; readonly searchKey: "ti_v3_execution_only_similar_trade_search"; readonly searchVersion: "v1"; readonly queryPlanDigest: CanonicalContentDigest; readonly resultDigest: CanonicalContentDigest; readonly partitionDigest: CanonicalContentDigest; readonly targetTradeKey: string; readonly dimensions: readonly SimilarTradeDimension[]; readonly candidateCount: string; readonly matchCount: string; readonly matches: readonly SimilarTradeMatch[]; readonly nearMisses: readonly SimilarTradeMatch[]; readonly summaryMetrics: readonly ExactMetricValue[]; readonly limitationCodes: readonly string[]; readonly searchDigest: CanonicalContentDigest; }

const MAXIMUM_RESULTS = 128;
const DIMENSIONS = new Set<SimilarTradeDimension>(["direction", "entry_price", "entry_time", "share_quantity", "entry_notional", "holding_time", "sequence_in_session", "previous_completed_outcome", "repeat_attempt", "symbol", "account"]);
function limit(value: unknown): bigint | null { if (typeof value !== "string" || !/^(?:0|[1-9][0-9]*)$/.test(value)) return null; const parsed = BigInt(value); return parsed <= BigInt(MAXIMUM_RESULTS) ? parsed : null; }
function takeBounded<T>(values: readonly T[], maximum: bigint): readonly T[] { const result: T[] = []; for (const value of values) { if (BigInt(result.length) >= maximum) break; result.push(value); } return Object.freeze(result); }
function ratioKey(value: QueryRowSemantics["entryPrice"]): string | null { return value === null ? null : `${value.numerator}/${value.denominator}`; }
function valueFor(row: QueryRowSemantics, dimension: SimilarTradeDimension): string | null { switch (dimension) { case "direction": return row.row.direction; case "entry_price": return ratioKey(row.entryPrice); case "entry_time": return row.entryTime; case "share_quantity": return ratioKey(row.shareQuantity); case "entry_notional": return ratioKey(row.entryNotional); case "holding_time": return row.holdingSecondsFloor.toString(); case "sequence_in_session": return row.sequenceInSession.toString(); case "previous_completed_outcome": return row.previousCompletedOutcome; case "repeat_attempt": return row.repeatAttempt.toString(); case "symbol": return row.row.stableInstrumentKey; case "account": return row.row.canonicalAccountKey; } }
function compareMatch(left: SimilarTradeMatch, right: SimilarTradeMatch): number { return left.unmatchedDimensions.length - right.unmatchedDimensions.length || left.unavailableDimensions.length - right.unavailableDimensions.length || compareUnicodeCodePoints(left.semanticRoundTripKey, right.semanticRoundTripKey); }
function asMatch(target: QueryRowSemantics, candidate: QueryRowSemantics, dimensions: readonly SimilarTradeDimension[]): SimilarTradeMatch { const matched: SimilarTradeDimension[] = []; const unmatched: SimilarTradeDimension[] = []; const unavailable: SimilarTradeDimension[] = []; for (const dimension of dimensions) { const targetValue = valueFor(target, dimension); const candidateValue = valueFor(candidate, dimension); if (targetValue === null || candidateValue === null) unavailable.push(dimension); else if (targetValue === candidateValue) matched.push(dimension); else unmatched.push(dimension); } return Object.freeze({ semanticRoundTripKey: candidate.row.semanticRoundTripKey, rowDigest: candidate.row.rowDigest, executionDigests: Object.freeze([...candidate.row.supportingExecutionDigests]), occurrenceKeys: Object.freeze([...candidate.row.supportingOccurrenceKeys]), matchedDimensions: Object.freeze(matched), unmatchedDimensions: Object.freeze(unmatched), unavailableDimensions: Object.freeze(unavailable), kind: unmatched.length === 0 && unavailable.length === 0 ? "match" : "near_miss" }); }

export function searchSimilarTrades(args: Readonly<{ readonly source: VerifiedTradeQueryDatasetSource; readonly partitionReceipt: AnalyticalPartitionReceipt; readonly result: unknown; readonly request: SimilarTradeSearchRequest; }>): { readonly ok: true; readonly value: SimilarTradeSearchResult } | { readonly ok: false; readonly error: AnalyticalContractFailure; } {
  const maximumMatches = limit(args.request.maximumMatches); const maximumNearMisses = limit(args.request.maximumNearMisses);
  if (maximumMatches === null || maximumNearMisses === null || args.request.dimensions.length === 0 || args.request.dimensions.length > DIMENSIONS.size || new Set(args.request.dimensions).size !== args.request.dimensions.length || args.request.dimensions.some((item) => !DIMENSIONS.has(item))) return contractFailure("ti_v3_analytics_contract_invalid", "$.request");
  const gateway = openReadOnlyTradeQueryGateway(args.source, args.partitionReceipt); if (!gateway.ok) return gateway;
  const result = verifyTradeQueryResultShape(args.result, gateway.value.authority); if (!result.ok || !isVerifiedTradeQueryExecution(args.result)) return contractFailure("ti_v3_analytics_contract_reference_mismatch", "$.result");
  const read = gateway.value.readBoundedRows(result.value.normalizedQueryPlan); if (!read.ok) return read;
  const semantics = buildQueryRowSemantics(read.value.rows); const target = semantics.find((item) => item.row.semanticRoundTripKey === args.request.targetTradeKey); if (target === undefined) return contractFailure("ti_v3_analytics_contract_reference_mismatch", "$.request.targetTradeKey");
  const filtered = applyTradeQueryFilters(semantics, args.request.filters).included.filter((item) => item.row.semanticRoundTripKey !== target.row.semanticRoundTripKey);
  const inspected = filtered.map((item) => asMatch(target, item, args.request.dimensions)).sort(compareMatch); const allMatches = inspected.filter((item) => item.kind === "match"); const allNearMisses = inspected.filter((item) => item.kind === "near_miss"); const matches = takeBounded(allMatches, maximumMatches); const nearMisses = args.request.includeNearMisses ? takeBounded(allNearMisses, maximumNearMisses) : [];
  const includedRows = semantics.filter((item) => matches.some((match) => match.semanticRoundTripKey === item.row.semanticRoundTripKey));
  const summaryMetrics = calculateTradeQueryMetrics(["candidate_count", "included_count", "excluded_count", "net_pnl", "average_pnl", "win_rate", "profit_factor"], includedRows, { candidateCount: String(filtered.length), includedCount: String(includedRows.length), excludedCount: String(filtered.length - includedRows.length) }, result.value.normalizedQueryPlan.authority.currency);
  const built = finalizeContentAddressedAuthority("trade_query_similarity_search", { schemaVersion: TRADE_QUERY_SIMILARITY_SEARCH_VERSION, searchKey: "ti_v3_execution_only_similar_trade_search", searchVersion: "v1", queryPlanDigest: result.value.normalizedQueryPlan.queryPlanDigest, resultDigest: result.value.resultDigest, partitionDigest: result.value.normalizedQueryPlan.authority.partitionDigest, targetTradeKey: args.request.targetTradeKey, dimensions: Object.freeze([...args.request.dimensions]), candidateCount: String(filtered.length), matchCount: String(allMatches.length), matches: Object.freeze(matches), nearMisses: Object.freeze(nearMisses), summaryMetrics, limitationCodes: Object.freeze([...(matches.length < allMatches.length ? ["ti_v3_similar_trade_matches_bounded"] : []), ...(nearMisses.length > 0 && nearMisses.length < allNearMisses.length ? ["ti_v3_similar_trade_near_misses_bounded"] : []), ...(matches.length === 0 ? ["ti_v3_similar_trade_zero_matches"] : [])].sort(compareUnicodeCodePoints)) }, "searchDigest");
  return built.ok ? { ok: true, value: built.value as SimilarTradeSearchResult } : built;
}
