import { describe, expect, it } from "vitest";
import {
  normalizePatternInputShape,
  type LegacyPatternInputShape,
  type PatternInput,
} from "../../pattern-input/types/pattern-input";
import { detectPatterns } from "../../pattern-detection/detect-patterns";
import { normalizeDetectedPatterns } from "../../pattern-normalization/normalize-detected-patterns";
import { buildPatternScoringInput } from "../builders/build-pattern-scoring-input";

function createBasePatternInput(
  overrides: Partial<LegacyPatternInputShape> = {},
): PatternInput {
  return normalizePatternInputShape({
    symbol: "ABCD",
    tradeDirection: "long",
    sessionBucket: "market_open",
    executionCount: 3,
    executionTimestamps: [
      "2024-04-12T13:33:30.000Z",
      "2024-04-12T13:36:15.000Z",
      "2024-04-12T13:39:10.000Z",
    ],
    firstExecutionTimestamp: "2024-04-12T13:33:30.000Z",
    lastExecutionTimestamp: "2024-04-12T13:39:10.000Z",
    tradeDurationSeconds: 340,
    tradeDurationMinutes: 5.666667,
    tradeCandleCount: 6,
    totalPositionIncreaseCount: 2,
    totalPositionDecreaseCount: 1,
    totalPositionUnchangedCount: 0,
    openedFromFlat: true,
    closedToFlat: true,
    hadMultipleIncreases: true,
    hadMultipleDecreases: false,
    maxPositionSize: 150,
    finalPositionSize: 0,
    entryPrice: 1.185,
    exitPrice: 1.295,
    tradeMfe: 0.175,
    tradeMae: 0.015,
    tradeMfePct: 0.147679,
    tradeMaePct: 0.012658,
    peakPriceDuringTrade: 1.36,
    worstPriceDuringTrade: 1.17,
    firstEntryPricePositionInTradeRangePct: 0.078947,
    firstEntryDistanceFromTradeLowPct: 0.06,
    firstEntryDistanceFromTradeHighPct: 0.01,
    firstEntryOccurredDuringMarketOpenSession: true,
    firstEntryOpeningRangeCandlesCountBeforeEntry: 3,
    firstEntryOpeningRangeHighBeforeEntry: 1.18,
    firstEntryOpeningRangeLowBeforeEntry: 1.1,
    firstEntryOccurredBeyondOpeningRangeInTradeDirection: false,
    firstEntryDistanceBeyondOpeningRangePct: null,
    firstEntryOpeningRangeReferenceLevelBeforeEntry: null,
    firstEntryOpeningRangeReferenceBreakDepthPctBeforeEntry: null,
    firstEntryHadOpeningRangeReclaimBeforeEntry: false,
    firstEntryOpeningRangeReclaimHeldIntoEntry: false,
    firstEntryOpeningRangeConfirmationCandlesCount: 0,
    firstEntryDistanceFromOpeningRangeReferenceLevelPct: null,
    firstEntryOccurredBeyondPreEntryRangeInTradeDirection: false,
    firstEntryDistanceBeyondPreEntryRangePct: null,
    firstEntryToPeakMovePct: 0.03,
    firstEntryToWorstMovePct: 0.012658,
    firstEntryCapturedPercentOfTradeMfe: 1,
    firstEntryWasNearTradeLow: true,
    firstEntryWasNearTradeHigh: false,
    firstEntryRecentRunUpPctBeforeEntry: 0.02,
    firstEntryRecentDropPctBeforeEntry: 0.01,
    firstEntryRecentNetMovePctBeforeEntry: 0.01,
    firstEntryRecentReferenceLevelBeforeEntry: 1.18,
    firstEntryRecentReferenceBreakDepthPctBeforeEntry: null,
    firstEntryHadRecentReferenceReclaimBeforeEntry: false,
    firstEntryRecentReferenceReclaimHeldIntoEntry: false,
    firstEntryRecentReferenceConfirmationCandlesCount: 0,
    firstEntryDistanceFromRecentReferenceLevelPct: null,
    firstEntryBullishCandlesBeforeEntryCount: 2,
    firstEntryBearishCandlesBeforeEntryCount: 1,
    firstEntryNearestSupportBelowPrice: 1.17,
    firstEntryNearestResistanceBelowPrice: 1.175,
    firstEntryNearestResistanceAbovePrice: 1.2,
    firstEntryDistanceToNearestSupportPct: 0.012658,
    firstEntryDistanceAboveNearestResistanceBelowPct: 0.008439,
    firstEntryDistanceToNearestResistancePct: 0.012658,
    firstEntryOccurredNearSupport: false,
    firstEntryOccurredNearResistance: false,
    firstEntryClearedNearestResistanceBelow: false,
    firstEntryHadRoomAboveAfterClearingResistance: false,
    firstEntryOccurredBelowNearestSupport: false,
    firstEntryOccurredInOpenAir: false,
    firstEntryNearestReferenceLevelLabel: null,
    firstEntryWasAboveVwap: true,
    firstEntryWasBelowVwap: false,
    firstEntryDistanceFromVwapPct: 0.01,
    firstEntryDistanceFromEma9Pct: 0.008,
    firstEntryDistanceFromEma20Pct: 0.015,
    firstEntryHasNearbyStructureOnBothSides: true,
    firstEntryDistanceBetweenNearestSupportAndResistancePct: 0.025,
    firstEntryResistanceLevelsAboveWithinClusterCount: 0,
    firstEntryHasStackedResistanceAbove: false,
    realizedReturnPct: 0.092827,
    realizedCapturePercentOfTradeMfe: 0.628564,
    favorableExcursionLeftOnTablePct: 0.054852,
    exitPricePositionInTradeRangePct: 0.657895,
    finalExitToPeakDistancePct: 0.050193,
    exitWasNearTradeHigh: false,
    exitWasNearTradeLow: false,
    postExitCandleCount: 1,
    maxFavorableMovePctAfterExit: 0.011583,
    maxAdverseMovePctAfterExit: 0.027027,
    netMovePctAtEndOfPostExitWindow: -0.019305,
    maxGivebackFromPeakOpenProfitPct: 0.2,
    partialExitCount: 1,
    hadPartialExit: true,
    maxFavorableMoveAfterPartialExitPct: 0.01,
    maxAdverseMoveAfterPartialExitPct: 0.01,
    reductionAbovePreviousAverageEntryCount: 1,
    reductionBelowPreviousAverageEntryCount: 0,
    averageReductionPriceVsPreviousAverageEntryPct: 0.04,
    averageReductionPricePositionInRecentRangePct: 0.82,
    reductionsNearRecentHighCount: 1,
    reductionsNearRecentLowCount: 0,
    averageReductionRecentRunUpPctBeforeExecution: 0.07,
    averageReductionRecentDropPctBeforeExecution: 0.01,
    reductionsWithRecentRunUpCount: 1,
    reductionsWithRecentDropCount: 0,
    readdAfterReductionCount: 0,
    hadReaddAfterReduction: false,
    averageReaddPriceChangeFromPriorReductionPct: null,
    averageFavorableMovePctAfterPartialExitBeforeReadd: null,
    averageAdverseMovePctAfterPartialExitBeforeReadd: null,
    averageFavorableMovePctAfterReaddBeforeNextExecution: null,
    averageAdverseMovePctAfterReaddBeforeNextExecution: null,
    readdsWithStrongerFavorableFollowthroughCount: 0,
    readdsWithStrongerAdverseFollowthroughCount: 0,
    readdsAfterRecentRunUpCount: 0,
    readdsAfterRecentDropCount: 0,
    peakOpenProfitPctOfBasis: 0.07,
    worstDrawdownPctOfBasis: -0.02,
    hadOpenLossBeforePeakOpenProfit: false,
    secondsFromFirstOpenLossToPeakOpenProfit: null,
    hadPeakOpenProfitBeforeWorstDrawdown: false,
    drawdownFromPeakOpenProfitPctOfBasis: null,
    hadReductionAfterPeakOpenProfitBeforeWorstDrawdown: false,
    reductionCountAfterPeakOpenProfitBeforeWorstDrawdown: 0,
    secondsFromPeakOpenProfitToWorstDrawdown: null,
    secondsFromPeakOpenProfitToFirstReduction: null,
    finalExitDistanceToNearestSupportPct: 0.02,
    finalExitDistanceToNearestResistancePct: null,
    finalExitOccurredNearSupport: false,
    finalExitOccurredNearResistance: false,
    finalExitSupportLevelsBelowWithinClusterCount: 0,
    finalExitHasStackedSupportBelow: false,
    reductionsNearSupportCount: 0,
    reductionsNearResistanceCount: 0,
    addsNearSupportCount: 0,
    addsNearResistanceCount: 0,
    addsAboveResistanceCount: 0,
    addsAboveResistanceWithRoomCount: 0,
    addsBelowSupportCount: 0,
    averageAddDistanceToNearestSupportPct: 0.02,
    averageAddDistanceToNearestResistancePct: 0.02,
    averageAddRoomToNextResistancePct: null,
    hadInsufficientCandleDataForStructuralContext: false,
    hadSupportResistanceContextAvailable: true,
    maxExecutionMfePct: 0.097046,
    maxExecutionMaePct: 0.027888,
    averageExecutionMfePct: 0.064098,
    averageExecutionMaePct: 0.022524,
    averageTimeBetweenExecutionsSeconds: 170,
    minTimeBetweenExecutionsSeconds: 165,
    maxTimeBetweenExecutionsSeconds: 175,
    averageCandlesBetweenExecutions: 3,
    executionsPerMinute: 0.529412,
    addCountAfterInitialEntry: 1,
    addAbovePreviousAverageEntryCount: 1,
    addBelowPreviousAverageEntryCount: 0,
    averageAddPriceVsPreviousAverageEntryPct: 0.05,
    averageAddPricePositionInRecentRangePct: 0.82,
    averageAddRecentRunUpPctBeforeExecution: 0.07,
    averageAddRecentDropPctBeforeExecution: 0.01,
    addsWithRecentRunUpCount: 1,
    addsWithRecentDropCount: 0,
    ...overrides,
  });
}

describe("buildPatternScoringInput", () => {
  it("builds Layer 4 input from the normalized Layer 3 contract", () => {
    const detectionResult = detectPatterns(createBasePatternInput());
    const normalizedResult = normalizeDetectedPatterns(detectionResult);
    const scoringInput = buildPatternScoringInput(normalizedResult);

    expect(scoringInput.normalizedPatternResult).toBe(normalizedResult);
    expect(scoringInput.topOverallAnchorPattern).toBe(
      normalizedResult.topOverallAnchorPattern,
    );
    expect(scoringInput.primaryPatternsByFamily.entry_quality.patternId).toBe(
      "advantaged_entry_structure",
    );
    expect(scoringInput.primaryPatternsByFamily.exit_quality).toBe(
      normalizedResult.primaryPatternsByFamily.exit_quality,
    );
    expect(scoringInput.primaryPatterns).toBe(normalizedResult.primaryPatterns);
    expect(scoringInput.supportingPatterns).toBe(
      normalizedResult.supportingPatterns,
    );
    expect(scoringInput.contextualPatterns).toBe(
      normalizedResult.contextualPatterns,
    );
    expect(scoringInput.prioritizedPatterns).toBe(
      normalizedResult.prioritizedPatterns,
    );
    expect(scoringInput.patternsByFamily).toBe(
      normalizedResult.patternsByFamily,
    );
    expect(scoringInput.primaryPatterns[0]).toHaveProperty("structuralLevel");
  });
});
