// =========================
// PATTERN SUPPRESSION GROUPS
// =========================
//
// PURPOSE:
// Registry of known overlap zones that Layer 3 should consider during
// normalization.

import { defineSuppressionGroup } from "./helpers";
import type { PatternSuppressionGroup } from "./types";

export const PATTERN_SUPPRESSION_GROUPS: PatternSuppressionGroup[] = [

  defineSuppressionGroup({
    groupId: "entry_low_location_overlap",
    description:
      "Low-side entry location overlap between broad and more specific entry patterns.",
      patternIds: [
        "low_range_entry",
        "entry_near_trade_low",
        "entry_near_support_structure",
        "entry_far_from_support_structure",
        "advantaged_entry_structure",
      ],
  }),

  defineSuppressionGroup({
    groupId: "entry_high_location_overlap",
    description:
      "High-side entry location overlap between broad and more specific entry patterns.",
      patternIds: [
        "high_range_entry",
        "entry_near_trade_high",
        "entry_under_resistance_structure",
        "breakout_with_room_above_structure",
        "breakout_into_overhead_resistance_structure",
        "breakout_with_room_above_and_constructive_final_exit",
        "breakout_with_room_above_and_failed_profit_protection",
        "recovery_with_breakout_with_room_above_and_constructive_final_exit",
        "recovery_with_breakout_with_room_above_and_failed_profit_protection",
        "breakout_into_overhead_resistance_with_defensive_final_exit",
        "breakout_into_overhead_resistance_with_failed_profit_protection",
        "recovery_with_breakout_into_overhead_resistance_and_defensive_final_exit",
        "recovery_with_breakout_into_overhead_resistance_and_failed_profit_protection",
        "disadvantaged_entry_structure",
      ],
  }),

  defineSuppressionGroup({
    groupId: "entry_quality_positive_overlap",
    description:
      "Positive entry-quality overlap between broad efficiency and richer advantaged structure.",
    patternIds: [
      "entry_with_favorable_remaining_upside",
      "efficient_entry_structure",
      "advantaged_entry_structure",
    ],
  }),

  defineSuppressionGroup({
    groupId: "entry_quality_negative_overlap",
    description:
      "Negative entry-quality overlap between limited-upside facts and richer disadvantaged structure.",
    patternIds: [
      "entry_with_limited_remaining_upside",
      "inefficient_entry_structure",
      "disadvantaged_entry_structure",
    ],
  }),

  defineSuppressionGroup({
    groupId: "entry_context_directional_overlap",
    description:
      "Directional pre-entry context overlaps with richer positive and negative entry-quality structures.",
    patternIds: [
      "entry_after_recent_run_up",
      "entry_after_recent_drop",
      "advantaged_entry_structure",
      "disadvantaged_entry_structure",
      "late_favorable_extension_entry_structure",
      "constructive_pullback_entry_structure",
      "disciplined_favorable_extension_entry_structure",
      "breakout_entry_structure",
      "measured_favorable_extension_entry_structure",
      "overextended_chase_entry_structure",
      "breakout_chase_entry_structure",
      "failed_breakout_entry_structure",
      "reclaim_entry_structure",
      "failed_reclaim_entry_structure",
      "mean_reversion_entry_structure",
      "failed_mean_reversion_entry_structure",
      "opening_range_breakout_entry_structure",
      "opening_range_breakout_chase_entry_structure",
      "failed_opening_range_breakout_entry_structure",
      "opening_range_reclaim_entry_structure",
      "failed_opening_range_reclaim_entry_structure",
      "market_open_breakout_entry_structure",
      "market_open_breakout_chase_entry_structure",
      "failed_market_open_breakout_entry_structure",
      "market_open_reclaim_entry_structure",
      "failed_market_open_reclaim_entry_structure",
      "weak_pullback_entry_structure",
      "deep_constructive_pullback_entry_structure",
      "deep_weak_pullback_entry_structure",
    ],
  }),

  defineSuppressionGroup({
    groupId: "position_build_vs_structure_overlap",
    description:
      "Overlap between raw position-building facts and richer lifecycle structure patterns.",
    patternIds: [
      "scaled_into_position",
      "single_build_position",
      "single_build_full_exit",
      "multi_build_full_exit",
      "multi_build_partial_exit",
      "scale_in_then_reduce",
      "one_and_done_round_trip",
    ],
  }),

  defineSuppressionGroup({
    groupId: "position_build_vs_scaling_quality_overlap",
    description:
      "Overlap between raw build facts and richer scaling-quality patterns.",
    patternIds: [
      "scaled_into_position",
      "single_build_position",
      "structured_position_building",
      "balanced_position_management",
      "one_sided_aggressive_building",
      "underutilized_position_building",
    ],
  }),

  defineSuppressionGroup({
    groupId: "scaling_quality_internal_overlap",
    description:
      "Internal overlap between broad and richer scaling-quality patterns.",
    patternIds: [
      "structured_position_building",
      "balanced_position_management",
      "one_sided_aggressive_building",
      "underutilized_position_building",
      "adding_above_prior_basis",
      "add_into_strength",
      "add_into_weakness",
      "add_after_recent_run_up",
      "add_after_recent_drop",
      "readd_after_reduction",
      "balanced_scaling_with_profit_protection",
      "constructive_readd_after_reduction",
      "balanced_management_with_constructive_exit",
      "recovery_with_balanced_management_and_constructive_final_exit",
      "balanced_management_with_missed_final_continuation",
      "recovery_with_balanced_management_and_missed_final_continuation",
      "timely_profit_protection_with_constructive_final_exit",
      "recovery_with_timely_profit_protection_and_constructive_final_exit",
      "trim_readd_with_constructive_final_exit",
      "trim_readd_with_missed_final_continuation",
      "constructive_recovery_after_early_adversity",
      "recovery_after_early_adversity_with_failed_protection",
      "recovery_after_early_adversity_with_stabilized_management",
      "repeated_trim_readd_with_constructive_management",
      "repeated_trim_readd_with_unstable_management",
      "repeated_rescue_attempts_with_renewed_deterioration",
      "late_chase_reentry_after_constructive_trim",
      "good_pullback_reentry_after_constructive_trim",
      "constructive_reentry_followthrough_after_trim",
      "constructive_reentry_with_constructive_final_exit",
      "recovery_with_constructive_final_exit_after_constructive_reentry",
      "deteriorating_reentry_after_trim",
      "repeated_trim_readd_with_constructive_reentry_followthrough",
      "repeated_trim_readd_with_deteriorating_reentry",
      "repeated_balanced_management_with_missed_final_continuation",
      "repeated_balanced_management_with_constructive_final_exit",
      "repeated_balanced_management_with_trim_into_resistance_and_constructive_final_exit",
      "repeated_balanced_management_with_trim_into_resistance_and_premature_final_exit",
      "repeated_balanced_management_with_exit_into_stacked_support_and_relief",
      "repeated_balanced_management_with_exit_into_thin_support_before_breakdown",
      "repeated_constructive_reentry_with_premature_final_exit",
      "repeated_balanced_management_with_premature_final_exit",
      "repeated_balanced_management_with_stop_like_forced_exit_after_breakdown",
      "repeated_balanced_management_with_stop_like_forced_exit_before_rebound",
      "repeated_constructive_reentry_with_constructive_final_exit",
      "repeated_deteriorating_reentry_with_defensive_final_exit",
      "repeated_rescue_attempts_with_balanced_management_and_constructive_final_exit",
      "repeated_rescue_attempts_with_premature_final_exit_after_constructive_reentries",
      "repeated_rescue_attempts_with_balanced_management_and_premature_final_exit",
      "repeated_rescue_attempts_with_balanced_management_and_missed_final_continuation",
      "repeated_rescue_attempts_with_balanced_management_and_trim_into_resistance_and_constructive_final_exit",
      "repeated_rescue_attempts_with_balanced_management_and_trim_into_resistance_and_premature_final_exit",
      "repeated_rescue_attempts_with_balanced_management_and_exit_into_stacked_support_and_relief",
      "repeated_rescue_attempts_with_balanced_management_and_exit_into_thin_support_before_breakdown",
      "repeated_rescue_attempts_with_balanced_management_and_stop_like_forced_exit_after_breakdown",
      "repeated_rescue_attempts_with_balanced_management_and_stop_like_forced_exit_before_rebound",
      "repeated_rescue_attempts_with_constructive_final_exit_after_constructive_reentries",
      "repeated_rescue_attempts_with_defensive_final_exit_after_deteriorating_reentries",
      "repeated_trim_readd_with_constructive_final_exit",
      "repeated_trim_readd_with_fearful_final_exit",
      "repeated_trim_readd_with_defensive_final_exit_after_deterioration",
      "repeated_rescue_attempts_with_defensive_final_exit_after_deterioration",
      "repeated_trim_readd_with_premature_final_exit",
      "repeated_trim_readd_with_missed_final_continuation",
      "balanced_management_with_take_profit_into_resistance_and_constructive_final_exit",
      "recovery_with_balanced_management_and_take_profit_into_resistance_and_constructive_final_exit",
      "balanced_management_with_take_profit_into_resistance_and_premature_final_exit",
      "recovery_with_balanced_management_and_take_profit_into_resistance_and_premature_final_exit",
      "repeated_balanced_management_with_take_profit_into_resistance_and_constructive_final_exit",
      "repeated_balanced_management_with_take_profit_into_resistance_and_premature_final_exit",
      "repeated_rescue_attempts_with_balanced_management_and_take_profit_into_resistance_and_constructive_final_exit",
      "repeated_rescue_attempts_with_balanced_management_and_take_profit_into_resistance_and_premature_final_exit",
        "aggressive_adding_with_failed_profit_protection",
        "add_into_resistance_structure",
        "trim_into_resistance_with_constructive_final_exit",
        "trim_into_resistance_with_premature_final_exit",
        "recovery_with_trim_into_resistance_and_constructive_final_exit",
        "recovery_with_trim_into_resistance_and_premature_final_exit",
        "repeated_balanced_management_with_trim_into_resistance_and_constructive_final_exit",
        "repeated_balanced_management_with_trim_into_resistance_and_premature_final_exit",
        "repeated_rescue_attempts_with_balanced_management_and_trim_into_resistance_and_constructive_final_exit",
        "repeated_rescue_attempts_with_balanced_management_and_trim_into_resistance_and_premature_final_exit",
        "add_above_resistance_structure",
        "add_above_resistance_with_constructive_final_exit",
        "add_above_resistance_with_failed_profit_protection",
        "recovery_with_add_above_resistance_and_constructive_final_exit",
        "recovery_with_add_above_resistance_and_failed_profit_protection",
        "repeated_adds_above_resistance_with_constructive_final_exit",
        "repeated_adds_above_resistance_with_failed_profit_protection",
        "revenge_adding_after_weakness",
        "revenge_adding_with_failed_profit_protection",
        "readd_after_delayed_risk_response",
    ],
  }),

  defineSuppressionGroup({
    groupId: "reduction_management_overlap",
    description:
      "Overlap between broad reduction facts and richer reduction/profit-protection structures.",
    patternIds: [
      "scaled_out_of_position",
      "reduction_into_strength",
      "reduction_into_weakness",
      "profit_protection_present",
      "failed_profit_protection_structure",
      "reduction_after_recent_run_up",
      "reduction_after_recent_drop",
      "held_through_danger_after_peak_profit",
      "delayed_risk_response_after_peak_profit",
      "timely_risk_response_after_peak_profit",
      "timely_risk_response_with_profit_protection",
      "delayed_risk_response_with_failed_profit_protection",
    ],
  }),

  defineSuppressionGroup({
    groupId: "exit_capture_band_overlap",
    description:
      "Capture-band patterns represent alternative bands of the same exit capture concept.",
    patternIds: [
      "high_capture_exit_structure",
      "moderate_capture_exit_structure",
      "low_capture_exit_structure",
    ],
  }),
  defineSuppressionGroup({
    groupId: "exit_post_exit_outcome_overlap",
    description:
      "Overlap between broad exit descriptors and richer post-exit continuation or relief patterns.",
      patternIds: [
        "exit_with_limited_giveback",
        "exit_with_meaningful_giveback",
        "exit_into_support_structure",
        "exit_into_support_with_relief_after_exit",
        "exit_into_support_before_breakdown",
        "exit_into_stacked_support_with_relief_after_exit",
        "exit_into_thin_support_before_breakdown",
        "exit_into_resistance_with_reversal_after_exit",
        "exit_into_resistance_before_breakout",
        "stabilized_recovery_with_exit_into_stacked_support_and_relief",
        "stabilized_recovery_with_exit_into_resistance_and_reversal",
        "stabilized_recovery_with_exit_into_resistance_before_breakout",
        "stabilized_recovery_with_exit_into_thin_support_before_breakdown",
        "missed_post_exit_continuation",
        "exit_avoided_adverse_followthrough",
        "defensive_exit_after_deterioration",
      "premature_final_exit_after_constructive_management",
      "fearful_exit_after_weakening",
      "disciplined_defensive_exit",
      "stabilized_recovery_with_constructive_final_exit",
      "stabilized_recovery_with_premature_final_exit",
    ],
  }),
];
